name: 'Terraform'

on: 
  push:
    branches-ignore:
       - master
  pull_request:
   
env:
  DOCKER_REPOSITORY: bashox
  FRONTEND_IMAGE_NAME: revolgy-frontend
  BACKEND_IMAGE_NAME: revolgy-backend
  IMAGE_TAG: ${{ github.run_number }}
  CLUSTER_NAME: eks
  MIGRATIONS_IMAGE_NAME: revolgy-migrations


jobs:
  
 #lintng, testing and building
  lint-test-build:
    name: 'Lint. Test, Build'
    runs-on: ubuntu-latest
    if: github.event_name == 'push'


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setting up node
      run: echo "yes"
  
#deploying to staging for the qa team

  deploy-staging:
    name: 'deploy-staging'
    needs: [lint-test-build]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setting up node
      run: echo "staging"
        
  


#deploying to production after merging to master branch and when all checks have succeed
  deploy-prod:
    name: 'deploy-prod'
    needs: [deploy-staging]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setting up node
      run: echo "yes"
        
    

